version: "2.1"
services:

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall:/config
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - duckdns-config/env.txt
    volumes:
     - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  my-journal:
    build:
      context: ./my-journal-config
      dockerfile: dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testmysql
    ports:
      - "3301:3306"
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=testmariadb
    ports:
      - "3302:3306"
  admin:
    image: phpmyadmin
    container_name: admin
    environment: 
      - PMA_ARBITRARY=1
    ports:
      - "81:80"